In [161]:
import numpy as np 
import pandas as pd 
import tensorflow as tf 

In [162]:
tf.__version__

'2.8.0'

In [163]:
df = pd.read_csv("Churn_Modelling.csv")

In [164]:
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [165]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [166]:
print(y)

[1 0 1 ... 1 1 0]


In [167]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [168]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [169]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [170]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [171]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [172]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [173]:
ann = tf.keras.models.Sequential()

In [174]:
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [175]:
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [176]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [177]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [178]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100


250/250 [==============================] - 1s 823us/step - loss: 0.6387 - accuracy: 0.6519
Epoch 2/100
250/250 [==============================] - 0s 656us/step - loss: 0.4756 - accuracy: 0.7966
Epoch 3/100
250/250 [==============================] - 0s 625us/step - loss: 0.4498 - accuracy: 0.8029
Epoch 4/100
250/250 [==============================] - 0s 592us/step - loss: 0.4397 - accuracy: 0.8046
Epoch 5/100
250/250 [==============================] - 0s 581us/step - loss: 0.4333 - accuracy: 0.8045
Epoch 6/100
250/250 [==============================] - 0s 589us/step - loss: 0.4276 - accuracy: 0.8049
Epoch 7/100
250/250 [==============================] - 0s 581us/step - loss: 0.4232 - accuracy: 0.8077
Epoch 8/100
250/250 [==============================] - 0s 576us/step - loss: 0.4195 - accuracy: 0.8089
Epoch 9/100
250/250 [==============================] - 0s 565us/step - loss: 0.4143 - accuracy: 0.8095
Epoch 10/100
250/250 [==============================] - 0s 562us/step - loss: 0.4051 

In [179]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 6000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [180]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [181]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1537   70]
 [ 210  183]]


0.86